[
  ./options.nix
  ./keymaps.nix
  ./autocmds.nix
  ./ui.nix
  ./bufferline.nix
  ./neo-tree.nix
  ./fzf-lua.nix
  ./git.nix
  ./lualine.nix
  ./noice.nix
  ./indent-blankline.nix
  ./blink-cmp.nix
  ./conform.nix
  ./todo-comments.nix
  ./which-key.nix
  ./autopairs.nix
  ./mini-surround.nix
  ./lsp/lsp.nix
  ./lsp/languages.nix
]
